### **Procesamiento de datos**

El procesamiento de datos es una parte fundamental para asegurarnos de que el dataset esté limpio y listo para su uso en modelos predictivos. Vamos a aplicar técnicas de preprocesamiento de datos para limpiar y transformar el dataset.

Nos enfocaremos en las siguientes tareas:
- **Limpieza de datos**: Manejar valores faltantes y duplicados.
- **Codificación de variables categóricas**: Convertir variables categóricas en numéricas.
- **Escalado de características**: Normalizar las características para que tengan una escala similar, si es necesario.
- **Manejo de valores nulos**: Manejar valores nulos en el dataset, mediante eliminación o imputación.
- **Eliminación de datos duplicados**: Eliminar datos duplicados en el dataset.

### **Importación de librerías**

In [2]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder
import matplotlib.pyplot as plt
import seaborn as sns

### **Importación de datos del Dataset**

In [3]:
df = pd.read_csv('../data/raw/IA_PROPENSITY_TRAIN.csv', index_col=0)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
df.head()

     PRODUCTO TIPO_CARROCERIA COMBUSTIBLE Potencia TRANS        FORMA_PAGO ESTADO_CIVIL GENERO    OcupaciOn               PROVINCIA Campanna1 Campanna2 Campanna3  Zona_Renta REV_Garantia      Averia_grave QUEJA_CAC  COSTE_VENTA  km_anno  Mas_1_coche  Revisiones  Edad_Cliente  Tiempo
CODE
CLI1        A           TIPO1      FUEL 1     Baja     M           Contado       CASADO      M      Empresa                Asturias        SI        NO        NO  Medio-Bajo      NO DATA  Averia muy grave        SI         2892        0        False           2            18       0
CLI2        A           TIPO1      FUEL 1     Baja     M           Contado       CASADO      F      Empresa                  Toledo        NO        NO        NO  Medio-Bajo           SI                No        NO         1376     7187        False           2            53       0
CLI3        A           TIPO1      FUEL 1     Baja     M             Otros       CASADO      M      Empresa                  Lerida        NO        NO        NO       Medio      NO DATA                No        NO         1376        0         True           4            21       3
CLI4        A           TIPO1      FUEL 1     Baja     M  Financiera Marca       CASADO      F      Empresa                  Madrid        SI        NO        NO       Medio           SI  Averia muy grave        SI         2015     7256         True           4            48       5
CLI5        A           TIPO1      FUEL 1     Baja     M  Financiera Marca       CASADO      F  Funcionario  Santa Cruz de Tenerife        SI        NO        SI        Alto      NO DATA                No        NO         1818        0         True           3            21       3

In [4]:
df.shape

(58049, 23)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 58049 entries, CLI1 to CLI58048
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PRODUCTO         58049 non-null  object
 1   TIPO_CARROCERIA  58049 non-null  object
 2   COMBUSTIBLE      58049 non-null  object
 3   Potencia         58049 non-null  object
 4   TRANS            58049 non-null  object
 5   FORMA_PAGO       58049 non-null  object
 6   ESTADO_CIVIL     57159 non-null  object
 7   GENERO           57189 non-null  object
 8   OcupaciOn        58049 non-null  object
 9   PROVINCIA        58049 non-null  object
 10  Campanna1        58049 non-null  object
 11  Campanna2        58049 non-null  object
 12  Campanna3        58049 non-null  object
 13  Zona_Renta       44871 non-null  object
 14  REV_Garantia     58049 non-null  object
 15  Averia_grave     58048 non-null  object
 16  QUEJA_CAC        58049 non-null  object
 17  COSTE_VENTA      58049 non-null  int64
 18  km_anno          58049 non-null  int64
 19  Mas_1_coche      58049 non-null  bool
 20  Revisiones       58049 non-null  int64
 21  Edad_Cliente     58049 non-null  int64
 22  Tiempo           58049 non-null  int64
dtypes: bool(1), int64(5), object(17)
memory usage: 10.2+ MB

In [6]:
df.dtypes

PRODUCTO           object
TIPO_CARROCERIA    object
COMBUSTIBLE        object
Potencia           object
TRANS              object
FORMA_PAGO         object
ESTADO_CIVIL       object
GENERO             object
OcupaciOn          object
PROVINCIA          object
Campanna1          object
Campanna2          object
Campanna3          object
Zona_Renta         object
REV_Garantia       object
Averia_grave       object
QUEJA_CAC          object
COSTE_VENTA         int64
km_anno             int64
Mas_1_coche          bool
Revisiones          int64
Edad_Cliente        int64
Tiempo              int64
dtype: object

In [7]:
df.columns

Index(['PRODUCTO', 'TIPO_CARROCERIA', 'COMBUSTIBLE', 'Potencia', 'TRANS', 'FORMA_PAGO', 'ESTADO_CIVIL', 'GENERO', 'OcupaciOn', 'PROVINCIA', 'Campanna1', 'Campanna2', 'Campanna3', 'Zona_Renta', 'REV_Garantia', 'Averia_grave', 'QUEJA_CAC', 'COSTE_VENTA', 'km_anno', 'Mas_1_coche', 'Revisiones', 'Edad_Cliente', 'Tiempo'], dtype='object')

Nos disponemos a describir las variables incluidas en el dataset, utilizadas para el análisis de propensión de un cliente a comprar automóviles:


- **`CODE`** _(object)_ → Código único del cliente.
- **`PRODUCTO`** _(object)_ → Tipo de producto asociado al cliente.
- **`TIPO_CARROCERIA`** _(object)_ → Tipo de carrocería del vehículo.
- **`COMBUSTIBLE`** _(object)_ → Tipo de combustible utilizado.
- **`Potencia`** _(object)_ → Categoría de potencia del vehículo (Ej.: "Baja").
- **`TRANS`** _(object)_ → Tipo de transmisión (Ej.: manual, automática).
- **`FORMA_PAGO`** _(object)_ → Método de pago (Ej.: contado, financiera).
- **`ESTADO_CIVIL`** _(object, con valores nulos)_ → Estado civil del cliente.
- **`GENERO`** _(object, con valores nulos)_ → Género del cliente.
- **`OcupaciOn`** _(object)_ → Profesión del cliente (Ej.: "Funcionario", "Empresa").
- **`PROVINCIA`** _(object)_ → Ubicación geográfica del cliente.
- **`Campanna1`, `Campanna2`, `Campanna3`** _(object)_ → Posibles campañas de marketing asociadas al cliente.
- **`Zona_Renta`** _(object, con valores nulos)_ → Nivel socioeconómico del cliente.
- **`REV_Garantia`** _(object)_ → Indica si el cliente ha realizado revisiones en garantía.
- **`Averia_grave`** _(object, un valor nulo)_ → Historial de averías graves del vehículo.
- **`QUEJA_CAC`** _(object)_ → Indica si el cliente ha registrado una queja en atención al cliente.
- **`COSTE_VENTA`** _(int64)_ → Monto total de la venta (valor numérico).
- **`km_anno`** _(int64)_ → Kilómetros recorridos por año.
- **`Mas_1_coche`** _(bool)_ → Indica si el cliente tiene más de un coche.
- **`Revisiones`** _(int64)_ → Número de revisiones realizadas.
- **`Edad_Cliente`** _(int64)_ → Edad del cliente.
- **`Tiempo`** _(int64)_ → Tiempo en años desde que es cliente.

In [8]:
df.head(3)

     PRODUCTO TIPO_CARROCERIA COMBUSTIBLE Potencia TRANS FORMA_PAGO ESTADO_CIVIL GENERO OcupaciOn PROVINCIA Campanna1 Campanna2 Campanna3  Zona_Renta REV_Garantia      Averia_grave QUEJA_CAC  COSTE_VENTA  km_anno  Mas_1_coche  Revisiones  Edad_Cliente  Tiempo
CODE
CLI1        A           TIPO1      FUEL 1     Baja     M    Contado       CASADO      M   Empresa  Asturias        SI        NO        NO  Medio-Bajo      NO DATA  Averia muy grave        SI         2892        0        False           2            18       0
CLI2        A           TIPO1      FUEL 1     Baja     M    Contado       CASADO      F   Empresa    Toledo        NO        NO        NO  Medio-Bajo           SI                No        NO         1376     7187        False           2            53       0
CLI3        A           TIPO1      FUEL 1     Baja     M      Otros       CASADO      M   Empresa    Lerida        NO        NO        NO       Medio      NO DATA                No        NO         1376        0         True           4            21       3

### **Limpieza de datos**

Comenzamos abordando los **valores duplicados** en el dataset.

In [9]:
df.duplicated().sum()

np.int64(144)

In [10]:
df.drop_duplicates(inplace=True)

In [11]:
df.shape[0] # Filas tras eliminar duplicados

57905

Ahora vamos con las **filas nulas**, ya que los valores nulos pueden afectar el rendimiento de los modelos predictivos.

In [12]:
df.isnull().sum() # Valores nulos

PRODUCTO               0
TIPO_CARROCERIA        0
COMBUSTIBLE            0
Potencia               0
TRANS                  0
FORMA_PAGO             0
ESTADO_CIVIL         890
GENERO               860
OcupaciOn              0
PROVINCIA              0
Campanna1              0
Campanna2              0
Campanna3              0
Zona_Renta         13064
REV_Garantia           0
Averia_grave           1
QUEJA_CAC              0
COSTE_VENTA            0
km_anno                0
Mas_1_coche            0
Revisiones             0
Edad_Cliente           0
Tiempo                 0
dtype: int64

Viendo sus porcentajes, rellenamos con la moda `ESTADO_CIVIL`, `GENERO` y `Zona_Renta`. Y eliminamos las filas con valores nulos en `Averia_grave`.

In [13]:
# Rellenar valores nulos con 'Desconocido'
df['ESTADO_CIVIL'] = df['ESTADO_CIVIL'].fillna('Desconocido')
df['GENERO'] = df['GENERO'].fillna('Desconocido')
df['Zona_Renta'] = df['Zona_Renta'].fillna('Desconocido')
df['Averia_grave'] = df['Averia_grave'].fillna('Desconocido')

In [14]:
df.isnull().sum() # Valores nulos

PRODUCTO           0
TIPO_CARROCERIA    0
COMBUSTIBLE        0
Potencia           0
TRANS              0
FORMA_PAGO         0
ESTADO_CIVIL       0
GENERO             0
OcupaciOn          0
PROVINCIA          0
Campanna1          0
Campanna2          0
Campanna3          0
Zona_Renta         0
REV_Garantia       0
Averia_grave       0
QUEJA_CAC          0
COSTE_VENTA        0
km_anno            0
Mas_1_coche        0
Revisiones         0
Edad_Cliente       0
Tiempo             0
dtype: int64

### **Label Encoder**
A continuación utilizaremos la técnica de `Label Encoding`. Asegurándonos de que las variables categóricas se conviertan en numéricas.

In [15]:
label_col =  LabelEncoder()

for col in df.select_dtypes(include=['object']).columns:
    df[col] = label_col.fit_transform(df[col])

df.head()

      PRODUCTO  TIPO_CARROCERIA  COMBUSTIBLE  Potencia  TRANS  FORMA_PAGO  ESTADO_CIVIL  GENERO  OcupaciOn  PROVINCIA  Campanna1  Campanna2  Campanna3  Zona_Renta  REV_Garantia  Averia_grave  QUEJA_CAC  COSTE_VENTA  km_anno  Mas_1_coche  Revisiones  Edad_Cliente  Tiempo
CODE
CLI1         0                0            0         1      1           0             0       2          1          4          1          0          0           3             0             2          1         2892        0        False           2            18       0
CLI2         0                0            0         1      1           0             0       1          1         47          0          0          0           3             1             4          0         1376     7187        False           2            53       0
CLI3         0                0            0         1      1           3             0       2          1         30          0          0          0           2             0             4          0         1376        0         True           4            21       3
CLI4         0                0            0         1      1           2             0       1          1         32          1          0          0           2             1             2          1         2015     7256         True           4            48       5
CLI5         0                0            0         1      1           2             0       1          2         41          1          0          1           0             0             4          0         1818        0         True           3            21       3

In [16]:
# Verificar valores nulos
missing_values = df.isnull().sum()
print("Valores faltantes por columna:")
print(missing_values)

# Si hay valores faltantes, podemos imputarlos (por ejemplo, con la moda, media o median)
# En este caso, rellenamos los valores nulos con la moda de cada columna
for col in df.columns:
    if df[col].isnull().sum() > 0:
        mode_value = df[col].mode()[0]
        df[col] = df[col].fillna(mode_value)

# Verificar nuevamente si hay valores nulos
missing_values_after_imputation = df.isnull().sum()
print("Valores faltantes después de la imputación:")
print(missing_values_after_imputation)

Valores faltantes por columna:
PRODUCTO           0
TIPO_CARROCERIA    0
COMBUSTIBLE        0
Potencia           0
TRANS              0
FORMA_PAGO         0
ESTADO_CIVIL       0
GENERO             0
OcupaciOn          0
PROVINCIA          0
Campanna1          0
Campanna2          0
Campanna3          0
Zona_Renta         0
REV_Garantia       0
Averia_grave       0
QUEJA_CAC          0
COSTE_VENTA        0
km_anno            0
Mas_1_coche        0
Revisiones         0
Edad_Cliente       0
Tiempo             0
dtype: int64
Valores faltantes después de la imputación:
PRODUCTO           0
TIPO_CARROCERIA    0
COMBUSTIBLE        0
Potencia           0
TRANS              0
FORMA_PAGO         0
ESTADO_CIVIL       0
GENERO             0
OcupaciOn          0
PROVINCIA          0
Campanna1          0
Campanna2          0
Campanna3          0
Zona_Renta         0
REV_Garantia       0
Averia_grave       0
QUEJA_CAC          0
COSTE_VENTA        0
km_anno            0
Mas_1_coche        0
Revisiones         0
Edad_Cliente       0
Tiempo             0
dtype: int64

Vamos a analizar los valores atípicos con el rango intercuartílico y a normalizar las variables continuas.

In [19]:
def remove_outliers(df, col):
    Q1 = df[col].quantile(0.1)
    Q3 = df[col].quantile(0.9)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]

# Detectar y eliminar outliers para las columnas numéricas
for col in df.select_dtypes(include=['float64', 'int64']).columns:
    df = remove_outliers(df, col)


# Ver los datos después de eliminar los outliers
print("Datos después de eliminar outliers:")
print(df.describe())

Datos después de eliminar outliers:
           PRODUCTO  TIPO_CARROCERIA   COMBUSTIBLE      Potencia    TRANS    FORMA_PAGO  ESTADO_CIVIL        GENERO  OcupaciOn     PROVINCIA     Campanna1     Campanna2     Campanna3    Zona_Renta  REV_Garantia  Averia_grave     QUEJA_CAC   COSTE_VENTA       km_anno    Revisiones  Edad_Cliente        Tiempo
count  48288.000000     48288.000000  48288.000000  48288.000000  48288.0  48288.000000  48288.000000  48288.000000    48288.0  48288.000000  48288.000000  48288.000000  48288.000000  48288.000000  48288.000000  48288.000000  48288.000000  48288.000000  48288.000000  48288.000000  48288.000000  48288.000000
mean       3.549515         3.015118      0.562044      1.529800      1.0      1.107770      0.916397      1.673335        1.0     25.725833      0.345055      0.121355      0.111581      1.456345      0.445287      2.714505      0.378417   2549.836543  11835.074925      3.668862     47.348617      1.855389
std        3.204413         2.781943      0.496141      0.762809      0.0      1.235324      1.622932      0.503373        0.0     15.310072      0.475391      0.326543      0.314853      1.186015      0.497003      1.449377      0.484997   1600.936678   9707.705299      2.548720     11.205149      3.091729
min        0.000000         0.000000      0.000000      0.000000      1.0      0.000000      0.000000      0.000000        1.0      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000      0.000000     18.000000      0.000000
25%        1.000000         0.000000      0.000000      1.000000      1.0      0.000000      0.000000      1.000000        1.0      8.000000      0.000000      0.000000      0.000000      0.000000      0.000000      2.000000      0.000000   1590.000000      0.000000      2.000000     40.000000      0.000000
50%        2.000000         3.000000      1.000000      2.000000      1.0      0.000000      0.000000      2.000000        1.0     31.000000      0.000000      0.000000      0.000000      1.000000      0.000000      4.000000      0.000000   2381.000000  11579.000000      3.000000     48.000000      0.000000
75%        8.000000         6.000000      1.000000      2.000000      1.0      2.000000      1.000000      2.000000        1.0     36.000000      1.000000      0.000000      0.000000      2.000000      1.000000      4.000000      1.000000   3356.000000  17914.250000      6.000000     56.000000      4.000000
max        9.000000         7.000000      1.000000      2.000000      1.0      3.000000      4.000000      2.000000        1.0     52.000000      1.000000      1.000000      1.000000      4.000000      1.000000      4.000000      1.000000  10808.000000  60242.000000     13.000000     71.000000     13.000000

In [20]:
# Verificar tipos de datos
print("Tipos de datos actuales:")
print(df.dtypes)

# Convertir las columnas que deberían ser numéricas, si es necesario
df['km_anno'] = pd.to_numeric(df['km_anno'], errors='coerce')
df['COSTE_VENTA'] = pd.to_numeric(df['COSTE_VENTA'], errors='coerce')

# Verificar nuevamente
print("Tipos de datos después de la conversión:")
print(df.dtypes)

Tipos de datos actuales:
PRODUCTO           int64
TIPO_CARROCERIA    int64
COMBUSTIBLE        int64
Potencia           int64
TRANS              int64
FORMA_PAGO         int64
ESTADO_CIVIL       int64
GENERO             int64
OcupaciOn          int64
PROVINCIA          int64
Campanna1          int64
Campanna2          int64
Campanna3          int64
Zona_Renta         int64
REV_Garantia       int64
Averia_grave       int64
QUEJA_CAC          int64
COSTE_VENTA        int64
km_anno            int64
Mas_1_coche         bool
Revisiones         int64
Edad_Cliente       int64
Tiempo             int64
dtype: object
Tipos de datos después de la conversión:
PRODUCTO           int64
TIPO_CARROCERIA    int64
COMBUSTIBLE        int64
Potencia           int64
TRANS              int64
FORMA_PAGO         int64
ESTADO_CIVIL       int64
GENERO             int64
OcupaciOn          int64
PROVINCIA          int64
Campanna1          int64
Campanna2          int64
Campanna3          int64
Zona_Renta         int64
REV_Garantia       int64
Averia_grave       int64
QUEJA_CAC          int64
COSTE_VENTA        int64
km_anno            int64
Mas_1_coche         bool
Revisiones         int64
Edad_Cliente       int64
Tiempo             int64
dtype: object

In [21]:
df['Mas_1_coche'].head(10)

CODE
CLI1     False
CLI2     False
CLI3      True
CLI4      True
CLI6     False
CLI7     False
CLI8     False
CLI9      True
CLI10     True
CLI11     True
Name: Mas_1_coche, dtype: bool

### **Exportación del dataset procesado**

Tras completar el preprocesamiento de los datos, es necesario guardar el dataset limpio y transformado para su uso en el modelo de clasificación. En esta etapa, aseguramos que todas las variables estén correctamente codificadas, sin valores nulos ni atípicos, y listas para ser utilizadas en el entrenamiento del modelo.

In [ ]:
df.to_csv('../data/stg/IA_PROPENSITY_TRAIN_1.csv', index=False)